export const MY_COUNTRIES_DATA = [
    { country:"Albania", countryCode:"ALB", region:"Europe", docType:"PAIDRE"},
    { country:"Angola", countryCode:"AGO", region:"Africa", docType:"PA"},
    { country:"Argentina", countryCode:"ARG", region:"South America", docType:"PA"},
    { country:"Armenia", countryCode:"ARM", region:"Asia", docType:"PA"},
    { country:"Australia", countryCode:"AUS", region:"Australia", docType:"PA"},
    { country:"Austria", countryCode:"AUT", region:"Europe", docType:"PAIDRE"},
    { country:"Bahrain", countryCode:"BHR", region:"Asia", docType:"PAID"},
    { country:"Belarus", countryCode:"BLR", region:"Europe", docType:"PA"},
    { country:"Belgium", countryCode:"BEL", region:"Europe", docType:"PAIDRE"},
    { country:"Brazil", countryCode:"BRA", region:"South America", docType:"PA"},
    { country:"Bosnia", countryCode:"BIH", region:"Asia", docType:"PAID"},   
    { country:"Bulgaria", countryCode:"BGR", region:"Europe", docType:"PAIDRE"},
    { country:"Canada", countryCode:"CAN", region:"North America", docType:"PA"},
    { country:"China", countryCode:"CHN", region:"Asia", docType:"PA"},
    { country:"Croatia", countryCode:"HRV", region:"Europe", docType:"PAIDRE"},
	{ country:"Cyprus", countryCode:"CYP", region:"Europe", docType:"PAIDRE"},
    { country:"Czech", countryCode:"CZE", region:"Europe", docType:"PAIDRE"},
    { country:"Denmark", countryCode:"DNK", region:"Europe", docType:"PARE"},
    { country:"Estonia", countryCode:"EST", region:"Europe", docType:"PAIDRE"},
    { country:"France", countryCode:"FRA", region:"Europe", docType:"PAIDRE"},
    { country:"Finland", countryCode:"FIN", region:"Europe", docType:"PAIDRE"},
    { country:"Germany", countryCode:"DEU", region:"Europe", docType:"PAIDRE"},
    { country:"Ghana", countryCode:"GHA", region:"Africa", docType:"PA"},
    { country:"Greece", countryCode:"GRC", region:"Europe", docType:"PAIDRE"},
    { country:"Hungary", countryCode:"HUN", region:"Europe", docType:"PAIDRE"},
    { country:"Iceland", countryCode:"ISL", region:"Europe", docType:"PAID"},
    { country:"India", countryCode:"IND", region:"Asia", docType:"PA"},
    { country:"Ireland", countryCode:"IRL", region:"Europe", docType:"PAID"},    
    { country:"Israel", countryCode:"ISR", region:"Asia", docType:"PA"},
    { country:"Italy", countryCode:"ITA", region:"Europe", docType:"PAIDRE"},
    { country:"Jamaica", countryCode:"JAM", region:"North America", docType:"PA"},
    { country:"Japan", countryCode:"JPN", region:"Asia", docType:"PA"},
    { country:"Kenya", countryCode:"KEN", region:"Africa", docType:"PA"},
    { country:"Latvia", countryCode:"LVA", region:"Europe", docType:"PAIDRE" },
    { country:"Lithuania", countryCode:"LTU", region:"Europe", docType:"PAIDRE"},
    { country:"Luxembourg", countryCode:"LUX", region:"Europe", docType:"PAIDRE"},    
    { country:"Malta", countryCode:"MLT", region:"Europe", docType:"PAID"},
    { country:"Mexico", countryCode:"MEX", region:"South America", docType:"PARE"},
    { country:"Morocco",countryCode:"MAR", region:"Africa", docType:"PA"},
    { country:"Monaco", countryCode:"MCO", region:"Europe", docType:"PA"},
    { country:"Netherlands", countryCode:"NLD", region:"Europe", docType:"PAIDRE"},
    { country:"New Zealand", countryCode:"NZL", region:"Australia", docType:"PAID"},
    { country:"Nigeria", countryCode:"NGA", region:"Africa", docType:"PA"}, 
    { country:"Norway", countryCode:"NOR", region:"Europe", docType:"PAIDRE"},
    { country:"Paraguay", countryCode:"PRY", region:"South America", docType:"PAID"},
    { country:"Peru", countryCode:"PER", region:"South America", docType:"PA"},
    { country:"Philippines", countryCode:"PHL", region:"Asia", docType:"PA"},
    { country:"Poland", countryCode:"POL", region:"Europe", docType:"PAIDRE"},
    { country:"Portugal", countryCode:"PRT", region:"Europe", docType:"PAIDRE"},
    { country:"Qatar", countryCode:"QAT", region:"Asia", docType:"PA"},
    { country:"Russian Federation", countryCode:"RUS", region:"Europe", docType:"PA"},
    { country:"Romania", countryCode:"ROU", region:"Europe", docType:"PAIDRE"},
    { country:"Rwanda", countryCode:"RWA", region:"Africa", docType:"PA"},  
    { country:"Saudi Arabia", countryCode:"SAU", region:"Asia", docType:"PA"},
    { country:"Senegal", countryCode:"SEN", region:"Africa", docType:"PA"},
    { country:"Singapore", countryCode:"SGP", region:"Asia", docType:"PA"},  
    { country:"Slovakia", countryCode:"SVK", region:"Europe", docType:"PAIDRE"},
    { country:"Spain", countryCode:"ESP", region:"Europe", docType:"PAIDRE"}, 
    { country:"South Korean", countryCode:"KOR", region:"Asia", docType:"PA"},
    { country:"South Africa", countryCode:"ZAF", region:"Africa", docType:"PARE"},
    { country:"Sweden", countryCode:"SWE", region:"Europe", docType:"PAIDRE"},
    { country:"Switzerland", countryCode:"CHE", region:"Europe", docType:"PAIDRE"},
    { country:"Thailand", countryCode:"THA", region:"Asia", docType:"PA"},
    { country:"Taiwan", countryCode:"TWN", region:"Asia", docType:"PA" },
    { country:"Tunisia", countryCode:"TUN",region:"Africa", docType:"PA"},
    { country:"Turkey", countryCode:"TUR", region:"Europe", docType:"PA"},
    { country:"Ukraine", countryCode:"UKN", region:"Europe", docType:"PA"},
    { country:"United Arab Emirates", countryCode:"ARE", region:"Asia", docType:"PA"},
    { country:"United Kingdom", countryCode:"GBR", region:"Europe", docType:"PARE"},
    { country:"United States", countryCode:"USA", region:"North America", docType:"PARE"},
    { country:"Viet Nam", countryCode:"VNM", region:"Asia", docType:"PA"},
]
export default MY_COUNTRIES_DATA;