export const MY_COUNTRIES_DATA = [
    { key: "af", value: "af", flag: "af" },
    { key: "ax", value: "ax", flag: "ax" },
    { key: "al", value: "al", flag: "al" },
    { key: "dz", value: "dz", flag: "dz" },
    { key: "as", value: "as", flag: "as" },
    { key: "ad", value: "ad", flag: "ad" },
    { key: "ao", value: "ao", flag: "ao" },
    { key: "ai", value: "ai", flag: "ai" },
    { key: "ag", value: "ag", flag: "ag" },
    { key: "ar", value: "ar", flag: "ar" },
    { key: "am", value: "am", flag: "am" },
    { key: "aw", value: "aw", flag: "aw" },
    { key: "au", value: "au", flag: "au" },
    { key: "at", value: "at", flag: "at" },
    { key: "az", value: "az", flag: "az" },
    { key: "bs", value: "bs", flag: "bs" },
    { key: "bh", value: "bh", flag: "bh" },
    { key: "bd", value: "bd", flag: "bd" },
    { key: "bb", value: "bb", flag: "bb" },
    { key: "by", value: "by", flag: "by" },
    { key: "be", value: "be", flag: "be" },
    { key: "bz", value: "bz", flag: "bz" },
    { key: "bj", value: "bj", flag: "bj" },
    { key: "bm", value: "bm", flag: "bm" },
    { key: "bt", value: "bt", flag: "bt" },
    { key: "bo", value: "bo", flag: "bo" },
    { key: "ba", value: "ba", flag: "ba" },
    { key: "bw", value: "bw", flag: "bw" },
    { key: "bv", value: "bv", flag: "bv" },
    { key: "br", value: "br", flag: "br" },
    { key: "vg", value: "vg", flag: "vg" },
    { key: "fr", value: "fr", flag: "fr" }
]
export default MY_COUNTRIES_DATA;